prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/lists/treemenu.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_256_rounded_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/contigencycheck.sql
@@application/shared_components/logic/application_processes/contingency_check.sql
@@application/shared_components/logic/application_processes/addtofavorite.sql
@@application/shared_components/logic/application_processes/loadimage.sql
@@application/shared_components/logic/application_processes/userguide.sql
@@application/shared_components/logic/application_processes/show_attachment.sql
@@application/shared_components/logic/application_items/app_role.sql
@@application/shared_components/logic/application_items/get_report_from_server.sql
@@application/shared_components/logic/application_items/gl_test.sql
@@application/shared_components/logic/application_items/gv_alert_text.sql
@@application/shared_components/logic/application_items/gv_center_type.sql
@@application/shared_components/logic/application_items/gv_client_id.sql
@@application/shared_components/logic/application_items/gv_connected_server.sql
@@application/shared_components/logic/application_items/gv_copy_right.sql
@@application/shared_components/logic/application_items/gv_cpt_id.sql
@@application/shared_components/logic/application_items/gv_cr_location_id.sql
@@application/shared_components/logic/application_items/gv_cr_zone_id.sql
@@application/shared_components/logic/application_items/gv_db_name.sql
@@application/shared_components/logic/application_items/gv_downloaded_path.sql
@@application/shared_components/logic/application_items/gv_emp_position_location_id.sql
@@application/shared_components/logic/application_items/gv_engine_kill.sql
@@application/shared_components/logic/application_items/gv_live_db.sql
@@application/shared_components/logic/application_items/gv_location_desc.sql
@@application/shared_components/logic/application_items/gv_location_id.sql
@@application/shared_components/logic/application_items/gv_login_time.sql
@@application/shared_components/logic/application_items/gv_order_location_desc.sql
@@application/shared_components/logic/application_items/gv_order_location_id.sql
@@application/shared_components/logic/application_items/gv_organization_id.sql
@@application/shared_components/logic/application_items/gv_pc_location.sql
@@application/shared_components/logic/application_items/gv_pc_order_location_id.sql
@@application/shared_components/logic/application_items/gv_physical_location.sql
@@application/shared_components/logic/application_items/gv_physical_location_id.sql
@@application/shared_components/logic/application_items/gv_rdt_server.sql
@@application/shared_components/logic/application_items/gv_read_only.sql
@@application/shared_components/logic/application_items/gv_reports_envid.sql
@@application/shared_components/logic/application_items/gv_store_id.sql
@@application/shared_components/logic/application_items/gv_terminal.sql
@@application/shared_components/logic/application_items/gv_text.sql
@@application/shared_components/logic/application_items/gv_user_department.sql
@@application/shared_components/logic/application_items/gv_user_department_id.sql
@@application/shared_components/logic/application_items/gv_user_id.sql
@@application/shared_components/logic/application_items/gv_user_location_id.sql
@@application/shared_components/logic/application_items/gv_user_mrno.sql
@@application/shared_components/logic/application_items/gv_user_name.sql
@@application/shared_components/logic/application_items/gv_zone_id.sql
@@application/shared_components/logic/application_items/is_mobile.sql
@@application/shared_components/logic/application_items/login_message.sql
@@application/shared_components/logic/application_items/mob_ver.sql
@@application/shared_components/logic/application_items/print_destination.sql
@@application/shared_components/logic/application_items/p_assignment_id.sql
@@application/shared_components/logic/application_items/p_doctor_type.sql
@@application/shared_components/logic/application_items/p_login_value.sql
@@application/shared_components/logic/application_items/p_ocpt_key.sql
@@application/shared_components/logic/application_items/p_page_id.sql
@@application/shared_components/logic/application_items/p_status_id.sql
@@application/shared_components/logic/application_items/p_task_mrno.sql
@@application/shared_components/logic/application_items/p_user_name.sql
@@application/shared_components/logic/application_items/report_url.sql
@@application/shared_components/logic/application_items/user_image.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/book_title_p5.sql
@@application/shared_components/user_interface/lovs/currency_p8.sql
@@application/shared_components/user_interface/lovs/library_members_list_p14.sql
@@application/shared_components/user_interface/lovs/lov_access_no.sql
@@application/shared_components/user_interface/lovs/lov_employee.sql
@@application/shared_components/user_interface/lovs/lov_journal_type.sql
@@application/pages/page_groups.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/drawer.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/page/skmtemplate.sql
@@application/shared_components/user_interface/templates/page/frontpage.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/button/save.sql
@@application/shared_components/user_interface/templates/button/report.sql
@@application/shared_components/user_interface/templates/button/btnprint.sql
@@application/shared_components/user_interface/templates/button/sign.sql
@@application/shared_components/user_interface/templates/button/btnapplychanges.sql
@@application/shared_components/user_interface/templates/button/exit.sql
@@application/shared_components/user_interface/templates/button/btnreset.sql
@@application/shared_components/user_interface/templates/button/btnadd.sql
@@application/shared_components/user_interface/templates/button/btnsearch.sql
@@application/shared_components/user_interface/templates/button/btncancel.sql
@@application/shared_components/user_interface/templates/button/btncreate.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/cards_container.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/image.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/inline_drawer.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/item_container.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/search_results_container.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/customstandardregion.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/list/mobile_menu.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/contextual_info.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/user_profile.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/label/leftlabeledcheckbox.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/security/authentications/oracle_apex_accounts.sql
@@application/shared_components/plugins/template_component/theme_101_avatar.sql
@@application/shared_components/plugins/template_component/theme_101_badge.sql
@@application/shared_components/plugins/template_component/theme_101_button.sql
@@application/shared_components/plugins/template_component/theme_101_comments.sql
@@application/shared_components/plugins/template_component/theme_101_content_row.sql
@@application/shared_components/plugins/template_component/theme_101_media_list.sql
@@application/shared_components/plugins/template_component/theme_101_timeline.sql
@@application/shared_components/plugins/dynamic_action/skm_call_report6370752912.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00100.sql
@@application/pages/page_00102.sql
@@application/pages/page_09999.sql
@@application/deployment/definition.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
